(cl:in-package grasp_execution_msgs-msg)
(cl:export '(GRASP-VAL
          GRASP
          IS_GRASP-VAL
          IS_GRASP
          IGNORE_EFFECTOR_POSE_UNGRASP-VAL
          IGNORE_EFFECTOR_POSE_UNGRASP
          GRIPPER_APPROACH_TRAJECTORY-VAL
          GRIPPER_APPROACH_TRAJECTORY
          GRIPPER_RETREAT_TRAJECTORY-VAL
          GRIPPER_RETREAT_TRAJECTORY
          GRASP_TRAJECTORY-VAL
          GRASP_TRAJECTORY
          USE_CUSTOM_TOLERANCES-VAL
          USE_CUSTOM_TOLERANCES
          EFFECTOR_POS_TOLERANCE-VAL
          EFFECTOR_POS_TOLERANCE
          EFFECTOR_ANGLE_TOLERANCE-VAL
          EFFECTOR_ANGLE_TOLERANCE
          JOINT_ANGLES_TOLERANCE-VAL
          JOINT_ANGLES_TOLERANCE
          CURR_EFFECTOR_POSE-VAL
          CURR_EFFECTOR_POSE
          CURR_JOINT_STATE-VAL
          CURR_JOINT_STATE
))