; Auto-generated. Do not edit!


(cl:in-package grasp_execution_msgs-msg)


;//! \htmlinclude GraspResult.msg.html

(cl:defclass <GraspResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil)
   (execution_time
    :reader execution_time
    :initarg :execution_time
    :type cl:real
    :initform 0))
)

(cl:defclass GraspResult (<GraspResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GraspResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GraspResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name grasp_execution_msgs-msg:<GraspResult> is deprecated: use grasp_execution_msgs-msg:GraspResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <GraspResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader grasp_execution_msgs-msg:success-val is deprecated.  Use grasp_execution_msgs-msg:success instead.")
  (success m))

(cl:ensure-generic-function 'execution_time-val :lambda-list '(m))
(cl:defmethod execution_time-val ((m <GraspResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader grasp_execution_msgs-msg:execution_time-val is deprecated.  Use grasp_execution_msgs-msg:execution_time instead.")
  (execution_time m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GraspResult>) ostream)
  "Serializes a message object of type '<GraspResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
  (cl:let ((__sec (cl:floor (cl:slot-value msg 'execution_time)))
        (__nsec (cl:round (cl:* 1e9 (cl:- (cl:slot-value msg 'execution_time) (cl:floor (cl:slot-value msg 'execution_time)))))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 0) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __nsec) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GraspResult>) istream)
  "Deserializes a message object of type '<GraspResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
    (cl:let ((__sec 0) (__nsec 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 0) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __nsec) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'execution_time) (cl:+ (cl:coerce __sec 'cl:double-float) (cl:/ __nsec 1e9))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GraspResult>)))
  "Returns string type for a message object of type '<GraspResult>"
  "grasp_execution_msgs/GraspResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GraspResult)))
  "Returns string type for a message object of type 'GraspResult"
  "grasp_execution_msgs/GraspResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GraspResult>)))
  "Returns md5sum for a message object of type '<GraspResult>"
  "20533aa1f02a989e1f44f0e5867bbe7c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GraspResult)))
  "Returns md5sum for a message object of type 'GraspResult"
  "20533aa1f02a989e1f44f0e5867bbe7c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GraspResult>)))
  "Returns full string definition for message of type '<GraspResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# successfully finished the grasp / ungrasp~%bool success~%~%# the final execution time~%duration execution_time~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GraspResult)))
  "Returns full string definition for message of type 'GraspResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# successfully finished the grasp / ungrasp~%bool success~%~%# the final execution time~%duration execution_time~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GraspResult>))
  (cl:+ 0
     1
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GraspResult>))
  "Converts a ROS message object to a list"
  (cl:list 'GraspResult
    (cl:cons ':success (success msg))
    (cl:cons ':execution_time (execution_time msg))
))
