set(_CATKIN_CURRENT_PACKAGE "moveit_controller_multidof")
set(moveit_controller_multidof_VERSION "1.0.4")
set(moveit_controller_multidof_MAINTAINER "Jennifer Buehler <jennifer.e.buehler@gmail.com>")
set(moveit_controller_multidof_PACKAGE_FORMAT "1")
set(moveit_controller_multidof_BUILD_DEPENDS "actionlib" "actionlib_msgs" "control_msgs" "geometry_msgs" "moveit_core" "moveit_msgs" "path_navigation_msgs" "pluginlib" "roscpp")
set(moveit_controller_multidof_BUILD_EXPORT_DEPENDS "actionlib" "actionlib_msgs" "control_msgs" "geometry_msgs" "moveit_core" "moveit_msgs" "path_navigation_msgs" "pluginlib" "roscpp")
set(moveit_controller_multidof_BUILDTOOL_DEPENDS "catkin")
set(moveit_controller_multidof_BUILDTOOL_EXPORT_DEPENDS )
set(moveit_controller_multidof_EXEC_DEPENDS "actionlib" "actionlib_msgs" "control_msgs" "geometry_msgs" "moveit_core" "moveit_msgs" "path_navigation_msgs" "pluginlib" "roscpp")
set(moveit_controller_multidof_RUN_DEPENDS "actionlib" "actionlib_msgs" "control_msgs" "geometry_msgs" "moveit_core" "moveit_msgs" "path_navigation_msgs" "pluginlib" "roscpp")
set(moveit_controller_multidof_TEST_DEPENDS )
set(moveit_controller_multidof_DOC_DEPENDS )
set(moveit_controller_multidof_URL_WEBSITE "")
set(moveit_controller_multidof_URL_BUGTRACKER "")
set(moveit_controller_multidof_URL_REPOSITORY "")
set(moveit_controller_multidof_DEPRECATED "")