// Generated by gencpp from file grasp_execution_msgs/GraspControlResult.msg
// DO NOT EDIT!


#ifndef GRASP_EXECUTION_MSGS_MESSAGE_GRASPCONTROLRESULT_H
#define GRASP_EXECUTION_MSGS_MESSAGE_GRASPCONTROLRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grasp_execution_msgs
{
template <class ContainerAllocator>
struct GraspControlResult_
{
  typedef GraspControlResult_<ContainerAllocator> Type;

  GraspControlResult_()
    : execution_time()
    , success(false)  {
    }
  GraspControlResult_(const ContainerAllocator& _alloc)
    : execution_time()
    , success(false)  {
  (void)_alloc;
    }



   typedef ros::Duration _execution_time_type;
  _execution_time_type execution_time;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::grasp_execution_msgs::GraspControlResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grasp_execution_msgs::GraspControlResult_<ContainerAllocator> const> ConstPtr;

}; // struct GraspControlResult_

typedef ::grasp_execution_msgs::GraspControlResult_<std::allocator<void> > GraspControlResult;

typedef boost::shared_ptr< ::grasp_execution_msgs::GraspControlResult > GraspControlResultPtr;
typedef boost::shared_ptr< ::grasp_execution_msgs::GraspControlResult const> GraspControlResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grasp_execution_msgs::GraspControlResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grasp_execution_msgs::GraspControlResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grasp_execution_msgs::GraspControlResult_<ContainerAllocator1> & lhs, const ::grasp_execution_msgs::GraspControlResult_<ContainerAllocator2> & rhs)
{
  return lhs.execution_time == rhs.execution_time &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grasp_execution_msgs::GraspControlResult_<ContainerAllocator1> & lhs, const ::grasp_execution_msgs::GraspControlResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grasp_execution_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::grasp_execution_msgs::GraspControlResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasp_execution_msgs::GraspControlResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_execution_msgs::GraspControlResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_execution_msgs::GraspControlResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_execution_msgs::GraspControlResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_execution_msgs::GraspControlResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grasp_execution_msgs::GraspControlResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da147b8123fb1e17e5e9698bb785b256";
  }

  static const char* value(const ::grasp_execution_msgs::GraspControlResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda147b8123fb1e17ULL;
  static const uint64_t static_value2 = 0xe5e9698bb785b256ULL;
};

template<class ContainerAllocator>
struct DataType< ::grasp_execution_msgs::GraspControlResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grasp_execution_msgs/GraspControlResult";
  }

  static const char* value(const ::grasp_execution_msgs::GraspControlResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grasp_execution_msgs::GraspControlResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"# the final execution time\n"
"duration execution_time\n"
"\n"
"# successfully done the grasp\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::grasp_execution_msgs::GraspControlResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grasp_execution_msgs::GraspControlResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.execution_time);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraspControlResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grasp_execution_msgs::GraspControlResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grasp_execution_msgs::GraspControlResult_<ContainerAllocator>& v)
  {
    s << indent << "execution_time: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.execution_time);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASP_EXECUTION_MSGS_MESSAGE_GRASPCONTROLRESULT_H
