// Generated by gencpp from file grasp_execution_msgs/GraspResult.msg
// DO NOT EDIT!


#ifndef GRASP_EXECUTION_MSGS_MESSAGE_GRASPRESULT_H
#define GRASP_EXECUTION_MSGS_MESSAGE_GRASPRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grasp_execution_msgs
{
template <class ContainerAllocator>
struct GraspResult_
{
  typedef GraspResult_<ContainerAllocator> Type;

  GraspResult_()
    : success(false)
    , execution_time()  {
    }
  GraspResult_(const ContainerAllocator& _alloc)
    : success(false)
    , execution_time()  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef ros::Duration _execution_time_type;
  _execution_time_type execution_time;





  typedef boost::shared_ptr< ::grasp_execution_msgs::GraspResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grasp_execution_msgs::GraspResult_<ContainerAllocator> const> ConstPtr;

}; // struct GraspResult_

typedef ::grasp_execution_msgs::GraspResult_<std::allocator<void> > GraspResult;

typedef boost::shared_ptr< ::grasp_execution_msgs::GraspResult > GraspResultPtr;
typedef boost::shared_ptr< ::grasp_execution_msgs::GraspResult const> GraspResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grasp_execution_msgs::GraspResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grasp_execution_msgs::GraspResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grasp_execution_msgs::GraspResult_<ContainerAllocator1> & lhs, const ::grasp_execution_msgs::GraspResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.execution_time == rhs.execution_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grasp_execution_msgs::GraspResult_<ContainerAllocator1> & lhs, const ::grasp_execution_msgs::GraspResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grasp_execution_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::grasp_execution_msgs::GraspResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasp_execution_msgs::GraspResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_execution_msgs::GraspResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_execution_msgs::GraspResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_execution_msgs::GraspResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_execution_msgs::GraspResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grasp_execution_msgs::GraspResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "20533aa1f02a989e1f44f0e5867bbe7c";
  }

  static const char* value(const ::grasp_execution_msgs::GraspResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x20533aa1f02a989eULL;
  static const uint64_t static_value2 = 0x1f44f0e5867bbe7cULL;
};

template<class ContainerAllocator>
struct DataType< ::grasp_execution_msgs::GraspResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grasp_execution_msgs/GraspResult";
  }

  static const char* value(const ::grasp_execution_msgs::GraspResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grasp_execution_msgs::GraspResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"# successfully finished the grasp / ungrasp\n"
"bool success\n"
"\n"
"# the final execution time\n"
"duration execution_time\n"
"\n"
;
  }

  static const char* value(const ::grasp_execution_msgs::GraspResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grasp_execution_msgs::GraspResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.execution_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraspResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grasp_execution_msgs::GraspResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grasp_execution_msgs::GraspResult_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "execution_time: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.execution_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASP_EXECUTION_MSGS_MESSAGE_GRASPRESULT_H
